config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'aboutme', to: 'pages#aboutme', as: 'aboutme'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Angelina Diener</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <%= yield %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/aboutme.html.erb
<h1>All Infos about me</h1>
<p>Angelina Diener</p>
<p>original Berliner</p>
<p>23 years old</p>
<p>Interests: </p>
<p>Good Coffee</p>
<p>Learning new dance moves</p>
<p>Artsy places</p>
<p>Faczinated by the ocean</p>
<p>Surfin</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<div class="navb">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "Resume", contact_path %></div>
  <div><%= link_to "Projects", aboutme_path %></div>
  <div><%= link_to "Contact", aboutme_path %></div>
  <div class="icon-links">
    <div><%= link_to 'Github', root_path %></div>
    <div><%= link_to 'Linkedin', root_path %></div>
  </div>
</div>